# frozen_string_literal: true

source 'https://rubygems.org'

gem 'faraday'
gem 'ferrum'
gem 'influxdb-client'
gem 'jwt'
gem 'watir'

group :development do
  gem 'awesome_print'
  gem 'pry-byebug'
end
